const DATA = {

  clusters: [
    { name: "Customer",      color: "#388E3C", textColor: "#fff" },
    { name: "Care Consumer", color: "#1565C0", textColor: "#fff" },
    { name: "Finance",       color: "#f5f925", textColor: "#1a1a2e" },
  ],

  domains: [
    // Customer – Green
    { name: "Reception",                       camel: "Reception",                    cluster: "Customer",      team: "Green 2" },
    { name: "Claim Orchestration",             camel: "ClaimOrchestration",           cluster: "Customer",      team: "Green 3" },
    { name: "Factoring",                       camel: "Factoring",                    cluster: "Customer",      team: "Green 1" },
    { name: "Costs and Tariffs",               camel: "CostsAndTariffs",              cluster: "Customer",      team: "Green 1" },
    { name: "Customer Configuration",          camel: "CustomerConfiguration",        cluster: "Customer",      team: "Green 1" },
    { name: "Vendor API",                      camel: "VendorAPI",                    cluster: "Customer",      team: "Green 2" },
    // Care Consumer – Blue
    { name: "Insurers",                        camel: "Insurers",                     cluster: "Care Consumer", team: "Blue 1"  },
    { name: "Templating and Messaging",        camel: "TemplatingAndMessaging",       cluster: "Care Consumer", team: "Blue 1"  },
    { name: "Invoicing and Dunning",           camel: "InvoicingAndDunning",          cluster: "Care Consumer", team: "Blue 2"  },
    { name: "Bailiff",                         camel: "Bailiff",                      cluster: "Care Consumer", team: "Blue 2"  },
    // Finance – Orange
    { name: "Banking",                         camel: "Banking",                      cluster: "Finance",       team: "Yellow 1" },
    { name: "Payment Matching",                camel: "PaymentMatching",              cluster: "Finance",       team: "Yellow 1" },
    { name: "Accounting",                      camel: "Accounting",                   cluster: "Finance",       team: "Yellow 1" },
    { name: "Frontend Infrastructure",         camel: "FrontendInfrastructure",       cluster: "Finance",       team: "Yellow 2" },
    { name: "Auditing",                        camel: "Auditing",                     cluster: "Finance",       team: "Yellow 2" },
    { name: "Authentication & User Management",camel: "AuthAndUserMgmt",              cluster: "Finance",       team: "Yellow 2" },
  ],

  entities: {
    "Reception": [
      { name: "Mediation",      camel: "Mediation"     },
      { name: "Validation",     camel: "Validation"    },
      { name: "Enrichers",      camel: "Enrichers"     },
      { name: "Claim File",     camel: "ClaimFile"     },
      { name: "IMD Input",      camel: "IMDInput"      },
    ],
    "Claim Orchestration": [
      { name: "Workflow",       camel: "Workflow"      },
      { name: "Claim",          camel: "Claim"         },
      { name: "Claim Status",   camel: "ClaimStatus"   },
      { name: "ARP",            camel: "ARP"           },
    ],
    "Factoring": [
      { name: "ARP",            camel: "ARP"           },
      { name: "Risk Assessment",camel: "RiskAssessment"},
      { name: "CHA",            camel: "CHA"           },
      { name: "BA Account",     camel: "BAAccount"     },
    ],
    "Costs and Tariffs": [
      { name: "Tariff",         camel: "Tariff"        },
      { name: "Pricing Plan",   camel: "PricingPlan"   },
      { name: "Rating",         camel: "Rating"        },
    ],
    "Customer Configuration": [
      { name: "Contract",       camel: "Contract"      },
      { name: "Product",        camel: "Product"       },
      { name: "Business Account",camel: "BusinessAccount"},
      { name: "Insurer Config", camel: "InsurerConfig" },
    ],
    "Vendor API": [
      { name: "Claim Receipt",  camel: "ClaimReceipt"  },
      { name: "Retrocession",   camel: "Retrocession"  },
      { name: "DPAYWS",         camel: "DPAYWS"        },
    ],
    "Insurers": [
      { name: "Clearing",             camel: "Clearing"           },
      { name: "Insurance Request",    camel: "InsuranceRequest"   },
      { name: "Insurance Answer",     camel: "InsuranceAnswer"    },
      { name: "IR Broker",            camel: "IRBroker"           },
      { name: "Insurance Receivable", camel: "InsuranceReceivable"},
    ],
    "Templating and Messaging": [
      { name: "Template",       camel: "Template"      },
      { name: "Notification",   camel: "Notification"  },
      { name: "BA Report",      camel: "BAReport"      },
      { name: "Debtor Report",  camel: "DebtorReport"  },
      { name: "Email",          camel: "Email"         },
      { name: "SMS",            camel: "SMS"           },
    ],
    "Invoicing and Dunning": [
      { name: "Invoice",        camel: "Invoice"       },
      { name: "Dunning",        camel: "Dunning"       },
      { name: "Claim",          camel: "Claim"         },
      { name: "Payment Page",   camel: "PaymentPage"   },
      { name: "Patient Portal", camel: "PatientPortal" },
      { name: "Bad Debtor",     camel: "BadDebtor"     },
    ],
    "Bailiff": [
      { name: "Bailiff Action", camel: "BailiffAction" },
      { name: "Debt Collection",camel: "DebtCollection"},
    ],
    "Banking": [
      { name: "Payment Agreement",     camel: "PaymentAgreement"     },
      { name: "Acquisition",           camel: "Acquisition"          },
      { name: "BA Invoice",            camel: "BAInvoice"            },
      { name: "Patient",               camel: "Patient"              },
      { name: "Credit",                camel: "Credit"               },
      { name: "Claim",                 camel: "Claim"                },
      { name: "Insurance Receivable",  camel: "InsuranceReceivable"  },
      { name: "Patient Portal",        camel: "PatientPortal"        },
      { name: "DPAYWS",                camel: "DPAYWS"               },
    ],
    "Payment Matching": [
      { name: "Matchable Item", camel: "MatchableItem" },
      { name: "Payment File",   camel: "PaymentFile"   },
      { name: "POF",            camel: "POF"           },
      { name: "CAMT",           camel: "CAMT"          },
      { name: "Matching",       camel: "Matching"      },
    ],
    "Accounting": [
      { name: "Ledger Connector",camel: "LedgerConnector"},
      { name: "Twinfield",      camel: "Twinfield"     },
      { name: "AFAS",           camel: "AFAS"          },
      { name: "Exact Online",   camel: "ExactOnline"   },
      { name: "Settlement",     camel: "Settlement"    },
      { name: "Booking",        camel: "Booking"       },
      { name: "GL Document",    camel: "GLDocument"    },
      { name: "Financial Statement", camel: "FinancialStatement" },
    ],
    "Frontend Infrastructure": [
      { name: "Claim API",      camel: "ClaimAPI"      },
      { name: "TIM UI",         camel: "TIMUI"         },
      { name: "InZicht",        camel: "InZicht"       },
    ],
    "Auditing": [
      { name: "Audit Log",      camel: "AuditLog"      },
      { name: "UI Audit",       camel: "UIAudit"       },
      { name: "Message Audit",  camel: "MessageAudit"  },
    ],
    "Authentication & User Management": [
      { name: "IAM",            camel: "IAM"           },
      { name: "IIP",            camel: "IIP"           },
      { name: "User Account",   camel: "UserAccount"   },
      { name: "Identity",       camel: "Identity"      },
    ],
  },

  // Suggested scenarios per "Domain|Entity" key (shown as datalist suggestions)
  scenarios: {
    "Banking|Payment Agreement":     ["Direct Debit", "iDEAL", "Standard Payment"],
    "Banking|Acquisition":           ["AP304 Direct Debit", "AP301 Direct Debit"],
    "Banking|BA Invoice":            ["Direct Debit", "Standard Payment", "Monthly Subscription"],
    "Banking|Patient":               ["Direct Debit"],
    "Banking|Credit":                ["Installment Direct Debit"],
    "Banking|Claim":                 ["Standard Payment"],
    "Banking|Insurance Receivable":  ["Standard Payment"],
    "Banking|Patient Portal":        ["Account", "Claim"],
    "Banking|DPAYWS":                ["File Status", "SSP Status", "Multi BA Login"],
    "Accounting|Ledger Connector":   ["Twinfield", "AFAS", "Exact Online", "Feed", "Upload"],
    "Accounting|Twinfield":           ["Feed", "Upload", "Statement"],
    "Accounting|AFAS":                ["Feed", "Upload", "Statement"],
    "Accounting|Exact Online":        ["Feed", "Upload", "Statement"],
    "Insurers|Clearing":             ["VR Request", "IR Request", "IRC Request", "VA Answer", "IA Answer", "Configure IRCR", "Stop Clearing"],
    "Insurers|IR Broker":            ["Configure IRCR", "Issue Request", "Receive Answer"],
    "Reception|Mediation":           ["AP301", "AP304", "DPAY PM304", "ClaimFile Delivery"],
    "Reception|Acquisition":         ["ClaimFile", "Validate", "Enrich", "Determine Debtor"],
    "Authentication & User Management|IAM": ["Symmetric Key", "SHA-1 Password"],
    "Authentication & User Management|User Account": ["DPAYWS User", "Portal User"],
    "Invoicing and Dunning|Invoice":  ["Monthly Subscription", "BA Invoice", "Printable", "eInvoice"],
    "Invoicing and Dunning|Dunning":  ["Reminder", "Collection Invoice", "Profit Letter", "Dun Debtor"],
    "Invoicing and Dunning|Bad Debtor": ["Transfer to Bailiff", "Agreement Term", "Stop Dunning"],
    "Banking|Payment Agreement":     ["Direct Debit", "iDEAL", "Standard Payment"],
    "Banking|Acquisition":           ["AP304 Direct Debit", "AP301 Direct Debit", "Order Out-Payment", "Order In-Payment"],
    "Banking|BA Invoice":            ["Direct Debit", "Standard Payment", "Monthly Subscription"],
    "Banking|Patient":               ["Direct Debit"],
    "Banking|Credit":                ["Installment Direct Debit", "Credit Request"],
    "Banking|Claim":                 ["Standard Payment", "Pre-Match", "Manual Match"],
    "Banking|Insurance Receivable":  ["Standard Payment"],
    "Banking|Patient Portal":        ["Account", "Claim", "Pay Online"],
    "Banking|DPAYWS":                ["File Status", "SSP Status", "Multi BA Login"],
    "Templating and Messaging|BA Report":    ["Send", "Generate", "Render"],
    "Templating and Messaging|Debtor Report":["Send", "Generate", "Render"],
    "Customer Configuration|Business Account":  ["Register", "Modify", "Contract", "Activation"],
    "Customer Configuration|Contract":          ["Activate", "End", "Modify", "Service Items"],
    "Insurers|Clearing":             ["VR Request", "IR Request", "IRC Request", "VA Answer", "IA Answer"],
    "Payment Matching|CAMT":         ["Batch DD", "Single Payment", "Reject DD"],
  },

  actions: [
    "Create", "Pay", "Reject", "Process", "Validate", "Match", "Update", "Delete",
    "Search", "Filter", "Export", "Import", "Send", "Receive", "Confirm", "Cancel",
    "Retry", "Break", "Link", "Route", "Calculate", "Generate", "Approve", "Assign",
    "Login", "Submit", "Request", "Get Status",
  ],

  results: [
    "Success", "Failed", "After Rejection", "Fail Authorization",
    "Before Batch DD", "Without Invoice", "With Invoice", "Wrong Amount",
    "After Rejection",
  ],

  // ── Smart Lookup index ────────────────────────────────────────────────────
  // keywords: all terms a user might type to reach this domain
  // aliases:  short codes / abbreviations from the Excel (bnm, lgc, clr…)
  // note:     brief label shown in search results
  lookup: [
    {
      domain: "Banking",
      aliases: ["bnm", "bm"],
      keywords: [
        "banking", "bank", "banking and matching", "payment agreement",
        "direct debit", "dd", "dpayws", "ideal", "idéal", "credit",
        "ba invoice", "patient", "patient portal", "insurance receivable",
        "order out-payment", "order in-payment", "mutation", "bank account", "statement",
        "ami", "installment", "pre-match payment", "manual match payment",
        "return code", "payer bank", "bank return", "credit payment", "debit payment",
        "i160876"
      ],
      note: "Banking & Matching (BnM) — DD, iDEAL, BA Invoice, Credit, Patient Portal"
    },
    {
      domain: "Payment Matching",
      aliases: ["bnm", "matching"],
      keywords: [
        "payment matching", "matching", "matchable item", "bank statement",
        "camt", "pof", "categorize", "manual match", "forward", "payback",
        "receivable", "payable", "payment file",
        "matching details", "possible matches", "match forward", "match payback",
        "matchable item type", "matching overview",
        "i160876"
      ],
      note: "Payment Matching (BnM) — CAMT, POF, Matchable Items, bank mutations"
    },
    {
      domain: "Accounting",
      aliases: ["lgc", "lc"],
      keywords: [
        "accounting", "ledger", "ledger connector", "twinfield", "afas",
        "exact online", "exact", "financial statement", "booking",
        "payment specification", "online ledger", "gl document",
        "financial booking", "charging", "send documents",
        "feed ledger", "feed general ledger", "feed online ledger",
        "financial control", "monitor ar", "ar balance",
        "failed booking", "retry booking", "booking failure", "ledger booking",
        "boekhouding", "prepare booking", "booking holiday",
        "i153828"
      ],
      note: "Accounting with Ledger Connector (LgC) — Twinfield, AFAS, Exact Online"
    },
    {
      domain: "Factoring",
      aliases: ["arp", "cha", "mdma"],
      keywords: [
        "factoring", "arp", "cha", "mdma", "risk", "risk assessment",
        "risk management", "bad debtor", "ap", "accounts payable",
        "ba accounts payable", "financial settlement", "settlement",
        "ba account", "charging",
        "rate and charge", "retrocede", "retrocession", "financial operations",
        "rate charge settle", "core arp",
        "daily settlements", "settlements overview", "financial settlement overview",
        "daily finance", "todo finance", "unsettled settlements", "settled settlements"
      ],
      note: "Factoring with Risk & CHA (MDMA) — ARP Accounts Payable, Risk, BA Account"
    },
    {
      domain: "Claim Orchestration",
      aliases: ["capi", "claimapi"],
      keywords: [
        "claim orchestration", "workflow", "claim routing", "routing",
        "claim api", "capi", "accounts receivable", "ar", "claim status",
        "ssp", "ssp status", "claim handling", "orchestration",
        "claim validation", "claim processing", "claim action",
        "trigger rule", "rule interpreter", "rule engine", "tim rule",
        "rule validation", "postpone claim", "claim postpone"
      ],
      note: "Claim Orchestration — Workflow, Claim Routing, SSP Status, Rules"
    },
    {
      domain: "Reception",
      aliases: ["med", "val", "acq", "inp"],
      keywords: [
        "reception", "mediation", "med", "acquisition", "acq",
        "claimfile", "claim file", "validation", "val", "enrichment",
        "enrichers", "imd", "imd input", "inp", "ap301", "ap304",
        "vektis", "mz", "zh", "ha", "os", "pm", "gds", "xml", "prerating",
        "file processing", "file delivery", "claim delivery",
        "deliver claimfile", "receive claimfile", "enrich claim",
        "buy claimfile", "take over risk", "determine debtor",
        "acquisition rule", "country code", "debtor record", "claim enrichment",
        "validation claim", "validation rule", "claim acquisition",
        "i153819"
      ],
      note: "Reception (Acquisition: Mediation, Validation, IMD) — ClaimFile, AP301/AP304"
    },
    {
      domain: "Insurers",
      aliases: ["clr", "irb"],
      keywords: [
        "insurers", "clearing", "clr", "irb", "irbroker", "insurance request",
        "vr", "ir", "ia", "va", "ircr", "retrocession", "clearable",
        "insurer", "insurance answer", "uzovi", "annotation",
        "vecozo", "vsp", "edp", "rejection level", "resultcode",
        "issue insurance request", "configure ircr", "clearable claimlines",
        "receive insurance answer", "stop clearing",
        "doctype", "clearable claim", "reminder clearing", "doctype reminder",
        "i153821"
      ],
      note: "Insurers (Clearing + IRBroker) — VR/IR/IA/VA, IRCR, Vecozo"
    },
    {
      domain: "Invoicing and Dunning",
      aliases: ["ind", "bad debtor"],
      keywords: [
        "invoicing", "dunning", "invoice", "ind", "print", "printable",
        "dunning stage", "patient portal", "rekening", "payment page",
        "printing data", "pdp", "debtor invoice", "ba report invoicing",
        "dun debtor", "invoice debtor", "transfer debt", "issue agreement term",
        "pay online", "request credit", "stop dunning",
        "digital portal", "invoice clearing", "digital invoice", "ideal invoice",
        "clearing invoice", "dunning letter", "payment agreement term",
        "bad debtor", "blockage",
        "i153822", "i153824"
      ],
      note: "Invoicing and Dunning (InD) — Invoice, Dunning, Payment Page (Rekening)"
    },
    {
      domain: "Bailiff",
      aliases: [],
      keywords: [
        "bailiff", "deurwaarder", "debt collection", "bad debtor collection",
        "debt", "bailiff action", "transfer to bailiff", "bailiff transfer",
        "ssp bailiff", "nota bailiff", "overdracht deurwaarder"
      ],
      note: "Bailiff — debt collection process"
    },
    {
      domain: "Templating and Messaging",
      aliases: ["rnn"],
      keywords: [
        "templating", "messaging", "rnn", "rendering", "notification",
        "template", "report", "message", "email", "letter", "notify",
        "ba report", "debtor report", "communication items",
        "sms", "pdf", "print template", "rendering and notification",
        "send ba report", "send debtor report", "notification facade",
        "mail template", "email template", "sms notification", "error notification",
        "email address", "notification message", "generate report"
      ],
      note: "Templating and Messaging (RnN) — Rendering, Notification, Reports"
    },
    {
      domain: "Costs and Tariffs",
      aliases: [],
      keywords: [
        "costs", "tariffs", "tariff", "pricing", "price", "rating",
        "rates", "cost", "catalog price", "tariff plan", "arp rating",
        "product pricing"
      ],
      note: "Costs and Tariffs — Pricing plans, Tariffs, ARP Rating"
    },
    {
      domain: "Customer Configuration",
      aliases: ["cat", "catalog"],
      keywords: [
        "customer configuration", "catalog", "configuration", "cat",
        "contract", "ba contract", "product", "platform", "catcfg",
        "customer config", "insurer config", "authorization",
        "controldata", "controldataprovider", "control data provider",
        "provider", "clearingdata", "business account",
        "product catalog", "ic authorization", "register ba contract",
        "catalog of customers", "catalog of insurers", "catalog of products",
        "define service template", "define price template",
        "catalog api", "contract settings", "contract relationships",
        "modify contract", "new contract", "business account settings",
        "third party connector", "thirdpartyconnector", "third party", "external connector",
        "i153825", "i153826", "i153827"
      ],
      note: "Customer Configuration (Catalog) — Products, Tariffs, BA Contracts"
    },
    {
      domain: "Vendor API",
      aliases: ["vendorapi", "claim receipt", "receipt", "retrocession"],
      keywords: [
        "vendor", "vendor api", "vendorapi", "retrocession", "claim receipt",
        "external vendor", "ba software", "vendor software",
        "inzicht vendor"
      ],
      note: "Vendor API — ClaimReceipt endpoint, Retrocession"
    },
    {
      domain: "Frontend Infrastructure",
      aliases: ["timui", "capi"],
      keywords: [
        "frontend", "frontend infra", "frontend infrastructure", "tim ui",
        "ui", "inzicht", "agent ui", "web ui", "spa", "views", "screens",
        "claim api frontend", "tim web ui", "agent",
        "interact with customer", "handle actionable claim", "enquire claimfile",
        "i153823"
      ],
      note: "Frontend Infrastructure — TIM UI, Agent UI, InZicht, Claim API views"
    },
    {
      domain: "Auditing",
      aliases: ["uia", "msa"],
      keywords: [
        "auditing", "audit", "uia", "msa", "message audit", "ui audit",
        "log", "monitor", "audit trail", "logging", "audit log",
        "audit data", "audit log sending", "imd audit"
      ],
      note: "Auditing — UI Audit (UIA) + Message Audit (MSA)"
    },
    {
      domain: "Authentication & User Management",
      aliases: ["iip", "iam"],
      keywords: [
        "authentication", "auth", "user management", "iip", "iam",
        "identity", "user", "login", "sso", "oauth", "clp", "user account",
        "identities", "auth management", "dpayws user", "portal user",
        "sha", "symmetric key", "facade", "manage identities", "identity provider",
        "create iam user", "delete iam user", "iam user", "password reset",
        "user role", "create user", "delete user", "assign role", "user permission"
      ],
      note: "Authentication & User Management (IIP/IAM) — Identity, SSO, User accounts"
    },
  ],

  // ── Component / service index (from IMF Mapping.xlsx · Component Catalog) ─
  // 411 components auto-generated: System Component → Domain + TIM Service
  // Scoring: words from name matching query = +2 pts each (≥2 needed for multi-word)
  //          timService words matching query = +1 pt each
  components: [
    { name: "TIM API DPayWS", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM API Mediation", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM_InfMedWS", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM_Mediation", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Mediation MediationChannelMonitor", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Mediation MediationFileConverter", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Mediation MediationFileDecomposer", domain: "Reception", timService: "Acq / Mediation [3.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM API Validation", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Reception ExternalHub", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimFileValidator", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidator", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorAddressEnricher", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorAgbEnricher", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorCoverEnricher", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorIMD", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorInsurerAgreementInterpreter", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorInterpreter", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorLineDescriptionEnricher", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorPreRating", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation ClaimValidatorSettledClaim", domain: "Claim Orchestration", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation CmdProcessor", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation CorrectionHandler", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation Expirator", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM Validation Interpreter", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD API Input", domain: "Reception", timService: "IMD / Input [4.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD_Input", domain: "Reception", timService: "IMD / Input [4.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD Input ChannelMonitor", domain: "Reception", timService: "IMD / Input [4.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD Input Converter", domain: "Reception", timService: "IMD / Input [4.1]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD TesterUI", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD WebUI", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD API Rules", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD API RulesTest", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD API Tester", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD_RuleCatalogue", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD_ValidationResultAudit", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD Gate", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD ValidationResultAudit", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "IMD Validator", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "ClaimFileGenerator", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "DPayWSTester", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "DPayWSTestTool", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "MediationApiTestSite", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Acquisition: Mediation, IMD Input & Validation" },
    { name: "TIM_Validation", domain: "Reception", timService: "Acq / Validation [3.2]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM API Enrichers", domain: "Reception", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM API Enrichers_debtor", domain: "Reception", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM_Enrichers", domain: "Reception", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM_EnrichersCover", domain: "Insurers", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM Enrichers AddressEnricher", domain: "Reception", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM Enrichers COVerEnricher", domain: "Insurers", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM Enrichers LineDescriptionEnricher", domain: "Reception", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "MiniCover", domain: "Insurers", timService: "Acq / Enrichers [3.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD DentalValidator", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD InsurerAgreementConnector", domain: "Reception", timService: "IMD / Validation [4.2]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD API Enrichers", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD_AGBRegister", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD_ProvisionsX", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD AgbEnricher", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD AgbUpdater", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD HistoryEnricher", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "IMD HistoryUpdater", domain: "Reception", timService: "IMD / Enrichers [4.3]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "BreGenerator", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "CodeReader", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Acquisition: Validation, Enrichers (TIM & IMD)" },
    { name: "TIM API ClaimReceipt", domain: "Vendor API", timService: "Vendor API [30]", serviceGroup: "Vendor API" },
    { name: "TIM API Retrocession", domain: "Vendor API", timService: "Vendor API [30]", serviceGroup: "Vendor API" },
    { name: "TIM_VendorAPI", domain: "Vendor API", timService: "Vendor API [30]", serviceGroup: "Vendor API" },
    { name: "TIM VendorAPI ClaimReceiptUpdater", domain: "Vendor API", timService: "Vendor API [30]", serviceGroup: "Vendor API" },
    { name: "TIM VendorAPI ClaimReceiptViewGenerator", domain: "Vendor API", timService: "Vendor API [30]", serviceGroup: "Vendor API" },
    { name: "TIM_Core", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM_Core | ACQ Validation Rules", domain: "Reception", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM_Core | Bad debtor (blocked/unblocked patient)", domain: "Factoring", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM_Core | Insurers", domain: "Insurers", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog ClearingDataProvider", domain: "Insurers", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog CmdProcessor", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog ControlDataProvider", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog Expirator", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog PreRater", domain: "Factoring", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog PreRaterUpdater", domain: "Factoring", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM Catalog Scheduler", domain: "Factoring", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM CustomerConfiguration CmdProcessor", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM CustomerConfiguration ContractSupervisor", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM CustomerConfiguration ThirdPartyConnector", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "ContractMigrator", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "ProductLoader", domain: "Customer Configuration", timService: "(Core) Catalog [1.1]", serviceGroup: "Catalog" },
    { name: "TIM API Catalog", domain: "Customer Configuration", timService: "Catalog (WebAPI) [1.2]", serviceGroup: "Catalog" },
    { name: "TIM API Catalog | ACQ Validation Rules", domain: "Reception", timService: "Catalog (WebAPI) [1.2]", serviceGroup: "Catalog" },
    { name: "TIM API Catalog | Bad debtor (blocked/unblocked patient)", domain: "Factoring", timService: "Catalog (WebAPI) [1.2]", serviceGroup: "Catalog" },
    { name: "TIM API Catalog | Insurers", domain: "Insurers", timService: "Catalog (WebAPI) [1.2]", serviceGroup: "Catalog" },
    { name: "TIM API CustomerConfigurationPrices", domain: "Customer Configuration", timService: "CustomerConfig [1.3]", serviceGroup: "Catalog" },
    { name: "TIM_Core.Charging", domain: "Factoring", timService: "(Core) Catalog [1.1]", serviceGroup: "ARP" },
    { name: "TIM_Core.Charging | BA", domain: "Factoring", timService: "(Core) Catalog [1.1]", serviceGroup: "ARP" },
    { name: "TIM_Core.Charging | Debtor", domain: "Claim Orchestration", timService: "(Core) Catalog [1.1]", serviceGroup: "ARP" },
    { name: "TIM ARP Charging", domain: "Factoring", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "TIM ARP Expirator", domain: "Factoring", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "TIM ARP Rating", domain: "Costs and Tariffs", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "TIM ARP SettlementUpdater", domain: "Factoring", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "TIM ARP SettlementUpdaterClearing", domain: "Factoring", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "TIM ARP SettlementUpdaterCmdProcessor", domain: "Factoring", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "TIM ARP Settling", domain: "Factoring", timService: "(Core) ARP [2]", serviceGroup: "ARP" },
    { name: "IMD API MdmaResponses", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD_MdmaData", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD_MdmaRaw", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD_MdmaResponses", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD MDMA FileLoader", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD MDMA FoClaimAnalyzer", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD MDMA FoClaimDecomposer", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD MDMA FoClaimUpdater", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "IMD MDMA ResponseGenerator", domain: "Factoring", timService: "IMD CHA (MDMA) [16]", serviceGroup: "MDMA (CHA)" },
    { name: "TIM API Clearing", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM_Clearing", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM_IRBroker", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "VecozoEmulator [DB]", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM Clearing Annotator", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM Clearing AnswerAnalyzer", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM Clearing CmdProcessor", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM Clearing Expirator", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM Clearing PaymentProcessor", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM Clearing RequestGenerator", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "AnswerFromIRBGenerator", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "AnswerGenerator", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "VecozoEmulator", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "VecozoFileViewer", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "VecozoLoader", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "VecozoTester", domain: "Insurers", timService: "Clearing [6.1]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM IRBroker AnswerConverter", domain: "Insurers", timService: "IRBroker [6.2 ]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM IRBroker ChannelMonitor", domain: "Insurers", timService: "IRBroker [6.2 ]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM IRBroker ChannelPublisher", domain: "Insurers", timService: "IRBroker [6.2 ]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM IRBroker RequestDeconverter", domain: "Insurers", timService: "IRBroker [6.2 ]", serviceGroup: "Clearing (w. IRB)" },
    { name: "TIM API InD", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM_InvoicingAndDunning", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM Invoice PaymentInvoiceStateService", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM Invoice PaymentSyncService", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM Invoice Scheduler", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning AnswerReader", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning CmdProcessor", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning DocumentDownloader", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning Expirator", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning InvoiceGenerator", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning InvoicePublisher", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning InvoiceUpdater", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM InvoicingAndDunning Scheduler", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM WebAPI Expirator", domain: "Invoicing and Dunning", timService: "Invoicing and Dunning (InD) [7]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM API Invoice", domain: "Invoicing and Dunning", timService: "Invoice WebAPI [9.3]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIMInvoiceWebGui", domain: "Invoicing and Dunning", timService: "Patient UI (rekening) [20]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIMInvoiceWebGui/HealthResponder", domain: "Invoicing and Dunning", timService: "Patient UI (rekening) [20]", serviceGroup: "Invoicing and Dunning (InD)" },
    { name: "TIM API BnM", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM_BnM", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM BnM BankingCmdProcessor", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM BnM CmdProcessor", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM BnM PaymentAutoMatcher", domain: "Payment Matching", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM BnM PaymentReader", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM BnM PaymentUpdater", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM BnM Scheduler", domain: "Banking", timService: "Banking and Matching (BnM) [5]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "TIM API RnN", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "TIM_RnN", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "TIM RnN CmdProcessor", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "TIM RnN EventHandler", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "TIM RnN MessageServer", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "TIM RnN NotificationServer", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "TIM RnN RenderingServer", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "KpnSmsEmulator", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "RnNTools", domain: "Templating and Messaging", timService: "Rendering and Notification (RnN) [8]", serviceGroup: "Rendering and Notification (RnN)" },
    { name: "CAMTGenerator", domain: "Banking", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "PaymentsCreator", domain: "Banking", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Banking and Matching (BnM)" },
    { name: "InZicht", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Ledger connector", domain: "Accounting", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | MATOMO", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | MBA overview", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Party annotations", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Settlement details page", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Translation", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Authentication", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Drupal and features", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Header and Footer", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Breadcrumb", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Search Patient", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Submitted ClaimFiles", domain: "Reception", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Actions Overview | Actions", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Actions Overview | Messages", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Latest Messages", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Financial Position", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Messages | Messages", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Messages | Message (popup)", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Other Messages | Other Messages List", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Other Messages | Other Messages Popup", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Chart / ClaimFile List", domain: "Reception", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | ClaimFile Details | Metadata / Amount / Costs", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | ClaimFile Details | Claims | Invalid / Accepted / Retroceded / Costs", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | ClaimFile Details | Costs | Metadata / Amount / Costs", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | All Claims | Claims", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Banner (Annotation)", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Metadata / Debtor / Amounts", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Add Annotation", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Copy Invoice", domain: "Invoicing and Dunning", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Stop Claim", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Ask Question", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Change Debtor Details", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | ClaimLines", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | Stop ClaimLines", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Submitted ClaimFiles | Claim Details | History", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Invalid Claims and ClaimLines | Invalid Claims and ClaimLines List", domain: "Reception", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Actions | Actions", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Actions | Action (inline): Stop, Postpone, Continue, Annotate", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Actions | Standard Actions (Notaregisseur)", domain: "Insurers", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Claims | Retrocessions | Retrocessions", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Search | Search Attributes / Patient List", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Details", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Details | Metadata / Counts (Amounts)", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Details | Claim List", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Blocked Patients | Blocked Patients / Unblocked Patients Lists", domain: "Bailiff", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Claim Annotations", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Claim Annotations | Digital Dunning Aborted (by Patient)", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Claim Annotations | Answers", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Claim Annotations | Debtor Risk", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Claim Annotations | Unconfirmed Digital Invoices", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Patients | Claim Annotations | Address Change Confirmation", domain: "Claim Orchestration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Financial Position", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Financial Position | Periods / Amounts", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Financial Position | Mutations", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Bailiff Cases | Claims in Bailiff List", domain: "Bailiff", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents", domain: "Templating and Messaging", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Ontvangstbevestiging (Confirmation Report)", domain: "Reception", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Betalingsspecificatie (Payment Specification)", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Verzoek tot aanzuivering (ROBP)", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Overzicht verrekende nota's (Paymspec Details)", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Jaaropgave (Yearly Report)", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Tarifering (???)", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Overeenkomst (Contract???)", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Overig (Other)", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Nota abonnementskosten", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | PM 35+", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Overviews | Documents | Retrocessieoverzicht", domain: "Factoring", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Contract Documents | Terms and Agreements / Documents", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Email Preferences | Email Address Preferences", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | Holidays | Register Holidays / Holidays List", domain: "Customer Configuration", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht | Home | External Links", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "InZicht API", domain: "Frontend Infrastructure", timService: "InZicht [19]", serviceGroup: "Customer UI (InZicht)" },
    { name: "TIM UI", domain: "Frontend Infrastructure", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2", domain: "Frontend Infrastructure", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Search Business Account | Party", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Name, Address, details, CoC... | Contracts & Party?", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Financial Status | BAFinancialPositions", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Contacts | PartyAnnotations", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Ledger | Settlements", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Files & Claims | ClaimFiles", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | SSP todo | ClaimActionables", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Contract & relationships | Activations", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Documents | Documents", domain: "Templating and Messaging", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | History | ContractHistory", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Business Account | Business Account details | Contract Notes", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | Add / edit BA details", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | Add / edit contract note agreements", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | Add / edit contract (activation, pricing, service items)", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | Add / edit practicioner", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | MBA management", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | Add Terms and condition", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Business Account details | Excluded Insurers", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Business Account details | Upload claim file", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Contract details", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Contract details | Service items edit", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Contract details | Pricing", domain: "Costs and Tariffs", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Claim finance details | Claim", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Claim insurer details | IRModels", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Claim BA details | Party", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Status management | Many...", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim client details | Patient/Debtor address details | Claim/Debtor & ClaimClient", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim client details | Debtor profile | DebtManagementRegistrations*", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim contacts | Debtor contacts | DebtorContactsOverview", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim contacts | Provider contacts | ClaimAnnotations", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim contacts | Insurer contacts | InsurerContactsOverview", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim line details | Claim lines | ClaimLines", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim line details | Claim costs | ClaimCosts", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Retrocessies and losses | Claim lines | ClaimRetrocessionOverview", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Add call", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Add address change", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Claim | Claim details | Add complaint", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim client details | Edit debtor details", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim client details | Edit Patient/Debtor address details", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Annotations | Add call", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Annotations | Add complaint", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Annotations | Add Address change", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Redeliver claim", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Stop claim/claimlines/costs", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Extend due date", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Copy invoice", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Create payment agreement", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Close from reserve/provision", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | CMIB deal", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Claim details | Event history | ClaimEvents", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Enricher | Address | Address", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | CodeLists | ResultCodeCatalog | ResultCodeCatalogues", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Insurer | Insurers | Insurers", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Insurer | Insurers | Insurer details | Many...", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Insurer | Problems | ClrProblemOverview", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Insurer | Request / Answers | IROverview", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Insurer | Request / Answers | IR / IA details | IRClaimOverview", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Insurer | Request / Answers | IR / IA details | PaymentsByMatching", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Insurer | Add contact party", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Insurer | View/Edit Care category Dental care", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Insurer - IR / IA Details | Notes", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Insurer - IR / IA Details | Bulk edit", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Rules | Acquisition | ValidationRuleOverview", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Rules | IRCR | Rules", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Rules - Acquisition | Overrides", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Rules - IRCR | Add / Edit rule", domain: "Insurers", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Rule interpreter | Rules overview | RuleInterpretationStatistics", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Rule interpreter | Rules overview | Rule details | Many...", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Rule interpreter | Rule changes | RuleInterpretationStatistics", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Provider ToDo | BAD files | ClaimFileAnnotations", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Provider ToDo | First delivery | ClaimFileAnnotations", domain: "Reception", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Provider ToDo | Follow up on reminder notes | PartyAnnotations", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Provider ToDo | BA messages | PartyAnnotations", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Claim ToDo | SSP Questions | ClaimAnnotations", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Claim ToDo | Reminder notes from patients calls | ClaimAnnotations", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | CMIB / Bailiff ToDo | Assess before Bailiff | ClaimAnnotations", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | CMIB / Bailiff ToDo | Closed Bailiff case | ClaimAnnotations", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Daily settlement overview | DailySettlementOverview", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Daily settlement overview - Details | Settlements", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Daily settlement overview - Details | PaymentOutgoingFiles", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Paybacks | MatchableItemOverviewPaybacks", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Paybacks | MatchableItem", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Paybacks | PaymentOutgoingFiles", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Forward to xxx | MatchableItemOverviewPaybacks", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Forward to xxx | MatchableItem", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Forward to xxx | PaymentOutgoingFiles", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Manual risk estimation | ClaimAnnotations", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Settlement messages | SettlementAnnotations", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | CHA Attentions list | PartyAnnotations", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Payment confirmation | PaymentClassificationsView", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Todo | Finance | Payment profits confirmation | PaymentByProfitSuggestions", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Finance | Change settlement", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Finance | Add financial correction", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Finance | Add warning", domain: "Factoring", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Todo | Approvals | PendingChanges", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Approvals | Reject approval", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Todo | Matching | Payments*", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Todo | Matching | Matching details | Payments, MatchableItemOverview*", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Matching | Start matching", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Matching | Assing selected paments", domain: "Banking", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Maintenance | Customer notification", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Maintenance | Customer notification | CustomerNotifications", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Maintenance | Objection reasons", domain: "Claim Orchestration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI 2 | Modals | Customer notification | New / edit notification", domain: "Customer Configuration", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM UI | Modals | Shared | Custom yes/no modal", domain: "Frontend Infrastructure", timService: "Agent UI (TIM UI) [17]", serviceGroup: "TIM UI (common framework)" },
    { name: "TIM_WebApi", domain: "Frontend Infrastructure", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low)", domain: "Frontend Infrastructure", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low) | Reception", domain: "Reception", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low) | Factoring", domain: "Factoring", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low) | Orchestration", domain: "Claim Orchestration", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low) | InD ???", domain: "Invoicing and Dunning", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low) | Insurers", domain: "Insurers", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM WebAPI ViewGenerator (Claim, Command, Low) | Matching", domain: "Payment Matching", timService: "Claim WebApi (backend) [9.1]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim", domain: "Frontend Infrastructure", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2", domain: "Frontend Infrastructure", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2 | Reception", domain: "Reception", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2 | Factoring", domain: "Factoring", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2 | Orchestration", domain: "Claim Orchestration", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2 | InD ???", domain: "Invoicing and Dunning", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2 | Insurers", domain: "Insurers", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API Claim_v2 | Matching", domain: "Payment Matching", timService: "Claim WebApi [9.2]", serviceGroup: "Claim API (common framework)" },
    { name: "TIM API AuditBrowser", domain: "Auditing", timService: "UI Audit [12.2]", serviceGroup: "UI Auditing" },
    { name: "TIM API AuditCsp", domain: "Auditing", timService: "UI Audit [12.2]", serviceGroup: "UI Auditing" },
    { name: "TIM_AuditTrail01", domain: "Auditing", timService: "UI Audit [12.2]", serviceGroup: "UI Auditing" },
    { name: "TIM Audit AuditTrail", domain: "Auditing", timService: "UI Audit [12.2]", serviceGroup: "UI Auditing" },
    { name: "TIM Audit ReaderAudit", domain: "Auditing", timService: "UI Audit [12.2]", serviceGroup: "UI Auditing" },
    { name: "CLP", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IIP", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IIP2", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "OssSupportService", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "TIM API FacadeAudit", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "TIM API FacadeNotification", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IdentityProvider", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IIPAuthConnector", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IIPAuthorization", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IIPAuthorization.Settings", domain: "Authentication & User Management", timService: "IIP [14.1]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "IAM", domain: "Authentication & User Management", timService: "IIP (IAM) [14.2]", serviceGroup: "Identity Provider (IIP with APIs, Facades, and IAMs)" },
    { name: "TIM API LedgerConnector", domain: "Accounting", timService: "Ledger Connector [10]", serviceGroup: "Ledger Connector" },
    { name: "TIM_LedgerConnector", domain: "Accounting", timService: "Ledger Connector [10]", serviceGroup: "Ledger Connector" },
    { name: "TIM LedgerConnector CommunicationService", domain: "Accounting", timService: "Ledger Connector [10]", serviceGroup: "Ledger Connector" },
    { name: "TIM LedgerConnector Expirator", domain: "Accounting", timService: "Ledger Connector [10]", serviceGroup: "Ledger Connector" },
    { name: "TIM LedgerConnector Feeder", domain: "Accounting", timService: "Ledger Connector [10]", serviceGroup: "Ledger Connector" },
    { name: "IMD_Audit", domain: "Auditing", timService: "Message Audit [12.1]", serviceGroup: "MSG Auditing" },
    { name: "TIM_Audit", domain: "Auditing", timService: "Message Audit [12.1]", serviceGroup: "MSG Auditing" },
    { name: "IMDAuditor", domain: "Auditing", timService: "Message Audit [12.1]", serviceGroup: "MSG Auditing" },
    { name: "TIM Audit MessageAuditor", domain: "Auditing", timService: "Message Audit [12.1]", serviceGroup: "MSG Auditing" },
    { name: "TIM Audit MessageMigrator", domain: "Auditing", timService: "Message Audit [12.1]", serviceGroup: "MSG Auditing" },
    { name: "TIMWebUI/HealthResponder", domain: "Frontend Infrastructure", timService: "Agent UI (TIM UI) [17]", serviceGroup: "Monitoring (ELK, Graf&Prom, PBI)" },
    { name: "A22986", domain: "Insurers", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "ACFilesGenerator", domain: "Insurers", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "AgbDataImporter", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "ClaimEditor", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "CustomerNotificationPlikoTworzator", domain: "Customer Configuration", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "CustomerNotificationSender", domain: "Customer Configuration", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "FeesGenerator", domain: "Costs and Tariffs", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "FileEnhancer", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "ForceIRB", domain: "Insurers", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "ICContractValidationApiMock", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "iDEALAuthHeaderGenerator", domain: "Invoicing and Dunning", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "JsonFileComparer", domain: "Customer Configuration", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "PermissionMatrixTool", domain: "Authentication & User Management", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "RulesCmd", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "TimCatalogMigration", domain: "Customer Configuration", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "TOGFileDataImporter", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "tools/CovEmulator", domain: "Insurers", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "tools/KpnSmsEmulator", domain: "Templating and Messaging", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "tools/VecozoEmulator", domain: "Insurers", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "tools/VektisApiEmulator", domain: "Customer Configuration", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "UnpackAndMakeAnswer", domain: "Insurers", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "ValidationTesterCmd", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "VektisApiEmulator", domain: "Customer Configuration", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
    { name: "ZH309Creator", domain: "Reception", timService: "Tools (Load, Generate, Emulate) [22]", serviceGroup: "Tools" },
  ],
};
